# Generated by Django 3.2.12 on 2023-01-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://assets.icanet.se/q_auto,f_auto/imagevaultfiles/id_48982/cf_259/catering_bild_saknas.png?', max_length=500),
        ),
    ]
